--Create user for login to Oracle
CREATE USER app_user IDENTIFIED BY 123456;

GRANT CREATE SESSION TO app_user;

GRANT SELECT, INSERT, UPDATE, DELETE ON USERS TO app_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON PRODUCTS TO app_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON ORDERS TO app_user;


--another users

CREATE USER vophatdat IDENTIFIED BY 15032005;

GRANT CREATE SESSION TO vophatdat;

GRANT SELECT, INSERT, UPDATE, DELETE ON USERS TO vophatdat;
GRANT SELECT, INSERT, UPDATE, DELETE ON PRODUCTS TO vophatdat;
GRANT SELECT, INSERT, UPDATE, DELETE ON ORDERS TO vophatdat;

-- checking status
SELECT username, account_status FROM dba_users WHERE username IN ('APP_USER', 'VOPHATDAT');
